services:
  api:
    build: 
      context: .
      dockerfile: local.Dockerfile
      target: api
    environment:
      MQ_HOST: rabbitmq
    ports:
      - "8080:8080"
      - "9229:9229"
    depends_on:
      main-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    develop:
      watch:
        - path: ./apps/api
          action: sync
          target: /app
          ignore: 
              - package.json
              - node_modules/

        - path: ./packages
          action: rebuild
          target: /app/packages
          ignore:
              - node_modules/

        - path: ./apps/api/package.json
          action: rebuild

  event-processor:
    build: 
      context: .
      dockerfile: local.Dockerfile
      target: event-processor
    environment:
      MQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    develop:
      watch:
        - path: ./apps/event-processor
          action: sync
          target: /app/apps/event-processor
          ignore:
              - node_modules/

        - path: ./packages
          action: sync
          target: /app/packages
          ignore:
              - node_modules/ 

        - path: ./apps/event-processor/package.json
          action: rebuild

  main-db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - .data/main-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DATABASE_MAIN}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  read-db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    volumes:
      - .data/read-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DATABASE_READ}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
  
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - .data/event-bus:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 3