services:
  main-db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./packages/main-db/.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devobank-main
      POSTGRES_USER: devobank
      POSTGRES_PASSWORD: devobank