services:
  main-db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - .data/main-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devobank-main
      POSTGRES_USER: devobank
      POSTGRES_PASSWORD: devobank

  queue:
    image: redis/redis-stack
    environment:
      REDIS_ARGS: "--requirepass devobank --user devobank on >devobank ~* allcommands --user default off nopass nocommands"
    ports:
      - "6379:6379"