services:
  api:
    build: 
      context: .
      dockerfile: ./apps/api/local.Dockerfile
    develop:
      watch:
        - path: ./apps/api
          action: sync
          target: /app
          ignore:
              - node_modules/

        - path: ./apps/api/package.json
          action: rebuild
    ports:
      - "3000:3000"
    depends_on:
      - main-db
      - rabbitmq

  main-db:
    image: postgres:17-alpine
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - .data/main-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
  
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - .data/event-bus:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}