services:
  main-db:
    image: postgres:17-alpine
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./packages/main-db/.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}