/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export interface Transaction {
  amount: Numeric;
  id: Generated<string>;
  transaction_type_id: string;
  user_id: string;
}

export interface TransactionType {
  id: Generated<string>;
  name: string;
}

export interface User {
  email: string;
  id: Generated<string>;
  password: string;
}

export interface DB {
  transaction_types: TransactionType;
  transactions: Transaction;
  users: User;
}
